apiVersion: skaffold/v2beta16
kind: Config

profiles:

  # Specify the profile name which you can run later using skaffold run -p <profilename>
  - name: my-profile-name
    build:
      tagPolicy:
        sha256: {}

      local:
        push: false

      artifacts:
        - image: 193048895737.dkr.ecr.us-west-1.amazonaws.com/taylorm/nanofibrous_budded
          context: .
          docker:
            dockerfile: Dockerfile
            buildArgs:
              GITHUB_TOKEN: '{{.GITHUB_TOKEN}}'
